### ISSUE TITLE
Error install on ubuntu server 

### ISSUE THREAD

**Issue by dbocart** [joone/loz#5]
Hello, 

i have these errors after install.sh or npm install loz :

```
bart@xxxxx:/home/git/loz$ sudo npm install loz -g
/usr/local/bin/loz -> /usr/local/lib/node_modules/loz/bin/index.js
npm WARN notsup Unsupported engine for dotenv@16.1.3: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: dotenv@16.1.3
npm WARN notsup Unsupported engine for yargs@17.7.2: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: yargs@17.7.2
npm WARN notsup Unsupported engine for cliui@8.0.1: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: cliui@8.0.1
npm WARN notsup Unsupported engine for yargs-parser@21.1.1: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: yargs-parser@21.1.1

+ loz@0.1.1
updated 85 packages in 13.153s
```

and when start loz command :
```

bart@xxxx:/home/git/loz$ loz
/usr/local/lib/node_modules/loz/node_modules/yargs-parser/build/index.cjs:1015
        throw Error(`yargs parser supports a minimum Node.js version of ${minNodeVersion}. Read our version support policy: https://github.com/yargs/yargs-parser#supported-nodejs-versions`);
        ^

Error: yargs parser supports a minimum Node.js version of 12. Read our version support policy: https://github.com/yargs/yargs-parser#supported-nodejs-versions
    at Object.<anonymous> (/usr/local/lib/node_modules/loz/node_modules/yargs-parser/build/index.cjs:1015:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/loz/node_modules/yargs/build/index.cjs:1:60570)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
bart@sdxxxx:/home/git/loz$
```

**Comment by dbocart** [comment]
it's now ok, it was on ubuntu 20.04 LTS, it's ok now after upgrade on 22.04 LTS
but now, i have

**Comment by joone** [comment]
You can now use ollama locally, so it doesn't cost any money."
